### PR TITLE
ci(scripts): add powershell script for git hook

### LINKED ISSUE #13: dev: add PowerShell script for git hooks and pre-commit
`scripts/setup-hooks.ps1` file:

```
#!/usr/bin/env pwsh
# Usage:
#   .\scripts\setup-hooks.ps1 (execute script)

# Function to enable a specific Git hook by copying its sample file
function Enable-Hook {
    param (
        [Parameter(Mandatory)][string]$HooksDir,
        [Parameter(Mandatory)][string]$HookName
    )

    $TargetHook = Join-Path $HooksDir $HookName
    $TemplateFile = Join-Path $HooksDir "$HookName.sample"

    if (Test-Path $TargetHook) {
        Write-Host "The '$HookName' hook is already enabled. ($TargetHook)" -ForegroundColor Yellow
    } elseif (Test-Path $TemplateFile) {
        Write-Host "Enabling '$HookName' hook..." -ForegroundColor Green
        Move-Item -Path $TemplateFile -Destination $TargetHook -Force
        Write-Host "Template hook copied to $TargetHook." -ForegroundColor Green
    } else {
        Write-Warning "Template for '$HookName' hook not found."
    }
}

# Function to get the Git hooks path
function Get-HooksPath {
    try {
        $GitRoot = git rev-parse --show-toplevel 2>$null
        $HooksPath = git rev-parse --git-path hooks 2>$null

        if ($GitRoot -and $HooksPath) {
            return Join-Path $GitRoot $HooksPath
        }
    } catch {
        Write-Warning "Unable to determine Git hooks path. Ensure this script is run inside a Git repository."
    }

    return ""
}

# Function to check if a command exists
function Command-Exists {
    param ([Parameter(Mandatory)][string]$Command)

    return $null -ne (Get-Command $Command -ErrorAction SilentlyContinue)
}

# Function to install pre-commit hooks
function Install-PreCommitHooks {
    param ([Parameter(Mandatory)][string[]]$HookTypes)

    foreach ($HookType in $HookTypes) {
        Write-Host "Installing '$HookType' pre-commit hook..." -ForegroundColor Cyan
        pre-commit install --hook-type $HookType
    }
}

# Function to install npm dependencies
function Install-NpmDependencies {
    if (Test-Path "package.json") {
        Write-Host "Installing npm dependencies..." -ForegroundColor Cyan
        npm install
    } else {
        Write-Host "No package.json found. Skipping npm dependency installation." -ForegroundColor Yellow
    }
}

# Main Script Execution
Write-Host "Starting setup-hooks script..." -ForegroundColor Cyan

# Check for required commands
if (-not (Command-Exists "pre-commit")) {
    Write-Error "pre-commit is not installed. Please install it first."
    exit 1
}

if ((-not (Command-Exists "npm")) -and (Test-Path "package.json")) {
    Write-Error "npm is not installed. Please install it first."
    exit 1
}

# Install pre-commit hooks
$PreCommitHooks = @("commit-msg", "prepare-commit-msg", "pre-merge-commit", "pre-push")
Install-PreCommitHooks -HookTypes $PreCommitHooks

# Enable additional Git hooks if hook path exists
$HooksDir = Get-HooksPath
if ($HooksDir) {
    Enable-Hook -HooksDir $HooksDir -HookName "pre-rebase"
} else {
    Write-Warning "Git hooks directory not found. Skipping additional hook setup."
}

# Install npm dependencies
Install-NpmDependencies

Write-Host "Setup-hooks script completed successfully." -ForegroundColor Green

```

### PR DESCRIPTION
**Pull request by ARiYaNSEp0-0**
this powershell script do following tasks:
- Install pre-commit hooks
- Enable additional Git hooks if hook path exists
- Install npm dependencies if package.json exists

closes #13 

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [x] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Checklist

- [ ] PR has an informative and human-readable title
- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Code can be automatically merged (no conflicts)
- [ ] Passes all existing automated tests
- [ ] Any _change_ in functionality is tested
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future todos are captured in comments
- [ ] Visually tested in supported browsers and devices (see checklist below :point_down:)
- [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
- [ ] Reviewers requested with
  the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

### CODE REVIEW

**Comment by HamidMolareza** [comment]
Did you test this on Windows? Was everything working correctly?

**Comment by HamidMolareza** [comment]
I create the below GitHub action and test it:
```
name: Test Setup-Hooks Script

on:
  workflow_dispatch:

jobs:
  test-script:
    runs-on: windows-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Install pre-commit
      - name: Install pre-commit
        run: |
          pip install pre-commit
          pre-commit --version

      # Install Node.js (for npm)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm --version

      # Ensure Git is installed
      - name: Check Git version
        run: git --version

      # Run the setup-hooks script
      - name: Execute setup-hooks script
        run: |
          pwsh ./scripts/setup-hooks.ps1

      - name: Invalid Commit
        run: |
          echo "sample content" > file.txt
          git add .
          git commit -m "Initial commit"
```

I got the output below, so everything seems fine.

```txt
Starting setup-hooks script...
Installing 'commit-msg' pre-commit hook...
pre-commit installed at .git\hooks\commit-msg
Installing 'prepare-commit-msg' pre-commit hook...
pre-commit installed at .git\hooks\prepare-commit-msg
Installing 'pre-merge-commit' pre-commit hook...
pre-commit installed at .git\hooks\pre-merge-commit
Installing 'pre-push' pre-commit hook...
pre-commit installed at .git\hooks\pre-push
Enabling 'pre-rebase' hook...
Template hook copied to D:\a\test-powershell\test-powershell\.git\hooks\pre-rebase.
Installing npm dependencies...

added 101 packages, and audited 102 packages in 7s

19 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Setup-hooks script completed successfully.
```

```
don't commit to branch...................................................Failed
- hook id: no-commit-to-branch
- exit code: 1

Error: Process completed with exit code 1.
```

**Review by HamidMolareza — APPROVED** [review]

**Comment by ARiYaNSEp0-0** [comment]
> Did you test this on Windows? Was everything working correctly?

The only problem was package.json installing. I put this powershell script inside scripts folder and it didn't find outer package.json to install it so I did it manually with ```npm install``` on root

**Comment by HamidMolareza** [comment]
Yes, this is designed to execute from the root, but it would be better to enhance this aspect.

**Comment by HamidMolareza** [comment]
Please check new codes.

**Comment by ARiYaNSEp0-0** [comment]
I removed the ```package-lock.json``` and also ```node_modules``` from root and  I ran the setup-hooks.ps1 script from scripts folder and It worked properly. thanks

**Pull request merged**
